remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [The Good and the Evil of Software and Hardware Verification]
description: [About Verification based on FO-logic and BMC based methods]
