#remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Software and Hardware Verification]
description: [About Formal Verification based on FO-logic and BMC based methods]


readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true
